# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(618, 836)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 241, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 241, 51))
        self.label_2.setObjectName("label_2")
        self.left_date = QtWidgets.QLineEdit(Form)
        self.left_date.setGeometry(QtCore.QRect(20, 60, 211, 31))
        self.left_date.setObjectName("left_date")
        self.right_date = QtWidgets.QLineEdit(Form)
        self.right_date.setGeometry(QtCore.QRect(370, 60, 211, 31))
        self.right_date.setObjectName("right_date")
        self.label_for_graph = QtWidgets.QLabel(Form)
        self.label_for_graph.setGeometry(QtCore.QRect(0, 190, 621, 461))
        self.label_for_graph.setText("")
        self.label_for_graph.setObjectName("label_for_graph")
        self.generate = QtWidgets.QPushButton(Form)
        self.generate.setGeometry(QtCore.QRect(200, 110, 201, 41))
        self.generate.setObjectName("generate")
        self.home = QtWidgets.QPushButton(Form)
        self.home.setGeometry(QtCore.QRect(190, 700, 241, 41))
        self.home.setObjectName("home")
        self.error = QtWidgets.QLabel(Form)
        self.error.setGeometry(QtCore.QRect(10, 780, 441, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.error.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Введите начальную дату</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Введите конечную дату</span></p></body></html>"))
        self.generate.setText(_translate("Form", "Построить"))
        self.home.setText(_translate("Form", "Вернуться на главный экран"))
